### ISSUE TITLE
Redesign Charging History

### ISSUE THREAD

**Issue by LilleKiwi** [AlexTelon/FlexiCharge-My-pages#93]

**Comment by Nvcxlx** [comment]
Expected outcome:
In addition to Profiles and Invoice, we need a new tab "**Charging History**" where all charging processes are listed with further information (_see screenshot_), possibly with a note as to whether this refuelling has already been paid for or not, so that we could include #2. 


![image](https://github.com/AlexTelon/FlexiCharge-My-pages/assets/140490220/c4d898c0-131a-4236-aa50-26bd3747f3e4)
(.\public\Flexicharge My pages figma.pdf)

**Comment by Nvcxlx** [comment]
filter function has been moved to issue #149
